# Generated by Django 5.0.1 on 2024-01-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('education', models.CharField(choices=[('высшее', 'Высшее'), ('среднее', 'Среднее'), ('любое', 'Любое')], max_length=255)),
                ('region', models.CharField(choices=[('москва', 'Москва'), ('санкт-петербург', 'Санкт-Петербург'), ('московская-область', 'Московская область'), ('нижегородская-область', 'Нижегородская область'), ('краснодарский-край', 'Краснодарский край')], max_length=255)),
                ('skills', models.TextField()),
                ('schedule', models.CharField(choices=[('полный-рабочий-день', 'Полный рабочий день'), ('сменный-график', 'Сменный график'), ('удаленная-работа', 'Удаленная работа'), ('свободный-график', 'Свободный график'), ('вахта', 'Вахта'), ('частичная-занятость', 'Частичная занятость')], max_length=255)),
            ],
        ),
    ]
